Repository zacdevil10/SpaceX-Launch-Tracker, pull requests merged in 2019-10, with the labels that each got.

#32 Added countdown to dashboard.
  app/build.gradle
  app/src/main/java/uk/co/zac_h/spacex/dashboard/DashboardFragment.kt
  app/src/main/java/uk/co/zac_h/spacex/dashboard/DashboardPresenter.kt
  app/src/main/java/uk/co/zac_h/spacex/dashboard/DashboardPresenterImpl.kt
  app/src/main/java/uk/co/zac_h/spacex/dashboard/DashboardView.kt
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#35 Launches layout
  app/build.gradle
  app/src/main/java/uk/co/zac_h/spacex/dashboard/DashboardFragment.kt
  app/src/main/java/uk/co/zac_h/spacex/dashboard/DashboardInteractorImpl.kt
  app/src/main/java/uk/co/zac_h/spacex/dashboard/adapters/DashboardLaunchesAdapter.kt
  app/src/main/java/uk/co/zac_h/spacex/dashboard/adapters/DashboardPinnedAdapter.kt
  app/src/main/java/uk/co/zac_h/spacex/launches/LaunchesListFragment.kt
  app/src/main/java/uk/co/zac_h/spacex/launches/adapters/LaunchesAdapter.kt
  app/src/main/java/uk/co/zac_h/spacex/launches/details/core/CoreDetailsFragment.kt
  app/src/main/java/uk/co/zac_h/spacex/launches/details/launch/LaunchDetailsFragment.kt
  app/src/main/java/uk/co/zac_h/spacex/statistics/graphs/padstats/PadStatsFragment.kt
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/fragment_launches_list.xml
  app/src/main/res/layout/list_item_dashboard_launches.xml
  app/src/main/res/layout/list_item_launches.xml
Labels: bug, enhancement

#37 Launch details links
  app/src/main/java/uk/co/zac_h/spacex/launches/adapters/LaunchLinksAdapter.kt
  app/src/main/java/uk/co/zac_h/spacex/launches/details/launch/LaunchDetailsFragment.kt
  app/src/main/java/uk/co/zac_h/spacex/launches/details/launch/LaunchDetailsView.kt
  app/src/main/java/uk/co/zac_h/spacex/utils/LinksModel.kt
  app/src/main/res/drawable/ic_assignment_black_24dp.xml
  app/src/main/res/drawable/ic_play_arrow_black_24dp.xml
  app/src/main/res/drawable/reddit.xml
  app/src/main/res/drawable/wikipedia.xml
  app/src/main/res/drawable/youtube.xml
  app/src/main/res/layout/fragment_launch_details.xml
  app/src/main/res/layout/list_item_launch_links.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#39 0.2.3
  app/build.gradle
  app/src/main/java/uk/co/zac_h/spacex/dashboard/DashboardFragment.kt
  app/src/main/java/uk/co/zac_h/spacex/dashboard/DashboardPresenterImpl.kt
  app/src/main/java/uk/co/zac_h/spacex/dashboard/DashboardView.kt
  app/src/main/java/uk/co/zac_h/spacex/launches/adapters/LaunchLinksAdapter.kt
  app/src/main/java/uk/co/zac_h/spacex/launches/details/launch/LaunchDetailsFragment.kt
  app/src/main/java/uk/co/zac_h/spacex/launches/details/launch/LaunchDetailsView.kt
  app/src/main/java/uk/co/zac_h/spacex/utils/LinksModel.kt
  app/src/main/res/drawable/ic_assignment_black_24dp.xml
  app/src/main/res/drawable/ic_play_arrow_black_24dp.xml
  app/src/main/res/drawable/reddit.xml
  app/src/main/res/drawable/wikipedia.xml
  app/src/main/res/drawable/youtube.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/fragment_launch_details.xml
  app/src/main/res/layout/list_item_launch_links.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  common/build.gradle
  common/src/main/java/uk/co/zac_h/spacex/utils/DateUtils.kt
Labels: version

#41 Create calendar events.
  app/src/main/java/uk/co/zac_h/spacex/launches/details/launch/LaunchDetailsFragment.kt
  app/src/main/res/drawable/ic_event_black_24dp.xml
  app/src/main/res/layout/fragment_launch_details.xml
Labels: enhancement

#46 Fix tab background color in Launches and Statistics page
  app/src/main/res/layout/fragment_launches.xml
  app/src/main/res/layout/fragment_statistics.xml
Labels: bug

#49 Notifications
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/uk/co/zac_h/spacex/utils/notifications/FirebaseMessagingService.kt
  app/src/main/java/uk/co/zac_h/spacex/utils/notifications/NextLaunchNotification.kt
  app/src/main/res/drawable/ic_spacex_icon.xml
Labels: enhancement

#50 Revert "Notifications"
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/uk/co/zac_h/spacex/utils/notifications/FirebaseMessagingService.kt
  app/src/main/java/uk/co/zac_h/spacex/utils/notifications/NextLaunchNotification.kt
  app/src/main/res/drawable/ic_spacex_icon.xml
Labels: invalid

#51 Notifications
  app/src/main/AndroidManifest.xml
  app/src/main/java/uk/co/zac_h/spacex/utils/notifications/FirebaseMessagingService.kt
  app/src/main/java/uk/co/zac_h/spacex/utils/notifications/NextLaunchNotification.kt
  app/src/main/res/drawable/ic_spacex_icon.xml
Labels: enhancement

#52 v0.4.1-beta
  app/build.gradle
  app/src/main/java/uk/co/zac_h/spacex/dashboard/DashboardInteractorImpl.kt
  common/build.gradle
Labels: version
